### ISSUE TITLE
Не строгое сравнение

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#1]
Привет! Расскажи пожалуйста почему тут
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/env_vars.ts#L4

и других местах используется не строгое сравнение?

**Comment by Vovencia** [comment]
Сравнивать строчное значение через строгое сравнение не вижу смысла, т.к. значение переменной либо такое же значение, либо будет false

В основном конфликты могут быть когда сравнивается числовое значение с строчным... но такой ситуации не может возникнуть, т.к. используется TypeScript (типизация) и будет конфликт

**Comment by MrKashlakov** [comment]
А почему не видишь смысла? не строгое быстрее? Зачем делать исключения для каких либо кейсов, так ведь можно допустить ошибку, которую не ожидаешь.

**Comment by Vovencia** [comment]
Как-то привык писать не строгое, так и пишу.. но в целом да, ты прав - лучше использовать строгое
