### ISSUE TITLE
Каскады стилей

### ISSUE THREAD

**Issue by NikitaRudenko** [Vovencia/WeatherStation#11]
API styled-components позволяет влиять на стили вложенных компонент, таким образом нет необходимости добавления классов.
https://www.styled-components.com/docs/advanced#referring-to-other-components

```
const WeatherItemStyled = styled(WeatherItem)`
	min-width: 280px;
	width: 16.666%;
	&,
	.weather-item__caption {
		font-size: ${ (props: IWeatherItemProps) => props.big ? '1.5rem' : '1.2rem' };
		font-weight: ${ (props: IWeatherItemProps) => props.big ? '400' : '500' };
	}
	.weather-item__icon {
		width: ${ (props: IWeatherItemProps) => props.big ? '60px' : '48px' };
	}
	.weather-item__content p {
		font-size: inherit;
	}
`
```

Вместо написания класса `weather-item__caption` можно передать компонент `WeatherItemCaption`.

**Comment by Vovencia** [comment]
Согласен, нужно так делать. Вот только почему-то в одной ситуации это работает, а в другой нет:
[http://joxi.ru/vAWzPznt14WXZ2](http://joxi.ru/vAWzPznt14WXZ2)

**Comment by Vovencia** [comment]
Нашел в чём была проблема - не внимательность.. всё работает)
