### ISSUE TITLE
Нет смысла тянуть свободные шрифты в проект

### ISSUE THREAD

**Issue by NikitaRudenko** [Vovencia/WeatherStation#12]
Зачем раздувать бандл непроприетарными шрифтами?

**Comment by Vovencia** [comment]
Загружать или не загружать - зависит от требований со стороны дизайна. В данном случае в теме Material UI используется Roboto и чтобы не отходить от задуманного дизайна я их подключил

**Comment by NikitaRudenko** [comment]
Всю статику вообще правильнее с cdn раздавать, чтобы не перегружать бандл.

**Comment by Vovencia** [comment]
Поправил на cdn
