### ISSUE TITLE
Использовать алиасы типов

### ISSUE THREAD

**Issue by NikitaRudenko** [Vovencia/WeatherStation#13]
Составные типы в сигнатуре читать сложно, код выглядит перегруженным. Алиасы типов решат эту проблему.
```
(() => Promise<any>)
&
((url: string) => Promise<any>)
&
((url: string, data: any) => Promise<any>)
```

**Comment by Vovencia** [comment]
С этим соглашусь, так лучше:
`function api(): Promise<any>;
function api(url: string): Promise<any>;
function api(url: string, data: any): Promise<any>;

function api(){
...`
