### ISSUE TITLE
Кластеризация?

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#2]
Расскажи пожалуйста что это за механизм? 
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/src/index.ts#L13

Это подготовка приложения к кластеризации?

**Comment by Vovencia** [comment]
Нет, в файле
> WeatherStation/WeatherStation-release/index.js

Я подключаю его как модуль, и использую как роутер, а не сервер

**Comment by MrKashlakov** [comment]
А почему тогда не разнести это просто по разным файлам? Было бы проще это читать и понимать.

**Comment by Vovencia** [comment]
В тот момент, когда я писал backend, я не задумался о том, что буду подключать как модуль.. а когда написал статический сервер, просто добавил это условие
