### ISSUE TITLE
Назначение файла

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#3]
Для чего в дальнейшем может понадобиться такой файл? 
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/webpack.config/_config.ts#L1

**Comment by Vovencia** [comment]
Было так сделано, чтобы все другие файлы брали конфигурацию из этого файла
а сам файл "env_vars" может быть достаточно далеко, например в "WeatherStation", для того, чтобы мог использоваться как в frontend, так и в backend

**Comment by MrKashlakov** [comment]
Ну в данной конкретной ситуации это имеет значение? Идея понятна, но реализация в конкретном кейсе кажется избыточной.

**Comment by Vovencia** [comment]
Сборщик который я использовал здесь, я скопировал из другого проекта, где данная логика использовалась.. и не менял логику, т.к. достаточно было только изменить пару значений в сборщике для данного проекта
