### ISSUE TITLE
Стиль именования переменных

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#4]
В этом файле все импортируемые переменные не имеют _ (нижнего подчеркивания), а эта имеет
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/webpack.config/index.ts#L6

Можешь рассказать почему?

**Comment by Vovencia** [comment]
там ниже переиспользуется переменная:
`const plugins = [].concat(_plugins);`

**Comment by MrKashlakov** [comment]
Так почему мы не можем уже импортировать нормальные плагины? Для чего эта логика?

**Comment by Vovencia** [comment]
В какой-то момент такая логика использовалась.
Поправил данную строчку
