### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#5]
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/src/index.ts#L16

Эту мидлвару стоило бы вынести в отельный метод, точно такой же код есть ниже.

**Comment by Vovencia** [comment]
Не подумал об этом, сделано:
[https://github.com/Vovencia/WeatherStation/blob/2840f1bb1375a55ce6e137045eaacdfbaf631d04/WeatherStation-backend/src/index.ts#L13](url)

`
	const applyAppMIddleware = (app) => {
		app.use(function(req, res, next) {
			res.header("Access-Control-Allow-Origin", "*");
			res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
			next();
		});

		app.use(helmet());
		app.use(shield());
		app.use(api);
	}

	if(isMainModule){
		app = express();

		applyAppMIddleware(app);
		
		app.listen(apiPort);

	} else {
		app = express.Router();

		applyAppMIddleware(app);
	}
`

**Comment by MrKashlakov** [comment]
👍
