### ISSUE TITLE
Назначение файла optimization.ts

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#6]
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/webpack.config/optimization.ts#L1

Почему этот файл остался в проекте? Для чего могла бы понадобиться оптимизация бандла на сервере?

**Comment by Vovencia** [comment]
Остался от frontend, можно удалить

**Comment by MrKashlakov** [comment]
Понял
