### ISSUE TITLE
Алиасы для модулей

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#7]
https://github.com/Vovencia/WeatherStation/blob/a2fcfa570c94ad58d222096575304406e277fb99/WeatherStation-backend/webpack.config/resolve.ts#L10

Для чего понадобились алиасы для системных модулей?

**Comment by MrKashlakov** [comment]
А, осознал что это не системный модуль. Как мне кажется, лучше избегать пересечения по названиям с системными модулями (built in Node.JS модулями), так стороннему разработчику сложно понять эти алиасы

**Comment by Vovencia** [comment]
Символ "@" в начале именования говорит о том, что это путь, а не название модуля

**Comment by MrKashlakov** [comment]
я про `source('utils')`
