### ISSUE TITLE
Использование интерфейсов

### ISSUE THREAD

**Issue by MrKashlakov** [Vovencia/WeatherStation#8]
Расскажи пожалуйста, почему это интерфейс
https://github.com/Vovencia/WeatherStation/blob/ac982de07942c70ed699e3aa9a4ff8b9ffc02ffe/WeatherStation-backend/src/interfaces/IResponse.ts#L1

Ведь интерфейс определяет множество разных типов имеющих что то общее типов в теории, а в данном контексте он используется просто как тип. Так же замети это и в React части проекта.  Там интерфейсы для описания стора были использованы. Почему не type?

**Comment by Vovencia** [comment]
Согласно этой статье [https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c](url) и этой записи [https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types](url)
Кардинального отличия между interface и type нет
По сути это разное написание одно и того же, кому как удобнее

**Comment by MrKashlakov** [comment]
Это относительно реализации интерфейсов в TS. Но давай взглянем на это шире, чаще всего у разработчика есть общая теория ООП в которой говорят что Interface это не то же самое что Type: https://ru.wikipedia.org/wiki/Интерфейс_(объектно-ориентированное_программирование)

**Comment by Vovencia** [comment]
> Таким образом, с одной стороны, интерфейс — это «договор», который обязуется выполнить класс, реализующий его, с другой стороны, интерфейс — это тип данных, потому что его описание достаточно чётко определяет свойства объектов, чтобы наравне с классом типизировать переменные. Следует, однако, подчеркнуть, что интерфейс не является полноценным типом данных, так как он задаёт только внешнее поведение объектов. Внутреннюю структуру и реализацию заданного интерфейсом поведения обеспечивает класс, реализующий интерфейс; именно поэтому «экземпляров интерфейса» в чистом виде не бывает, и любая переменная типа «интерфейс» содержит экземпляры конкретных классов.

В моей логике interface - объект, который имеет набор свойств/методов, который будет использоваться во взаимодействии, как собственно и говориться в приведённом предложении

А тип я использую только для обозначения реализации функции, например: type exampleFunction = (arg1: string) => ISomeValue;
