### ISSUE TITLE
Разные технологии описания стилей

### ISSUE THREAD

**Issue by NikitaRudenko** [Vovencia/WeatherStation#9]
В проекте используется stylus и styled-components.
Это избыточно, достаточно остановится на чем-то одном.
Чем было обусловлено такое решение?

**Comment by Vovencia** [comment]
Stylus используется только в одном месте, для установки каких-то глобальных стилей. А данном случае этих:
`html
	background #fafafa
body, #root, #root-placeholder
	height auto
	min-height 100%
*,
&:before,
&:after
	box-sizing padding-box
	box-sizing border-box`

**Comment by NikitaRudenko** [comment]
А ты проверял API styled-components на предмет метода установки глобальных стилей?

**Comment by Vovencia** [comment]
Как-то пропустил этот момент (createGlobalStyle), поправил в коде
